version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
deployment:
  staging:
    branch: master
    heroku:
      appname: funfunappp